dist: bionic

jobs:
  include:
  - name: Kong CE 2.4.x
    env: KONG_VERSION=2.4.x
  - name: Enterprise 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Enterprise Nightly
    env: KONG_VERSION=nightly-ee

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: TIq+SnufEVaVapZASHWFyRK2sC0zYqfsqa7GWDLMyP2ndmOttVer3RNGN3ZLoJUM+ErnK5c5TE1MlBW0P/Bj5UEz+8ABscstYOz0AaBR1peQumf7+BucA1bhLMAcEo2ieJGxOkPpWGDcM8ULI44s2uQCOM0F02+InYmgLdp54yC1Ss7aQqvLFeERas71cOVfchG6yOwZ6Ua+5rLPOxoBd1kL6iuvknAEYBvbJpxuYUy4VNSDhcL3xkSCmji+wWaB/7mfFcuTFEKMA1DHGXhysPJhdz/hHL0U0mLuSInyFgwq4ZWJL3XLcrYIPjZo3ex8CS5JnJ2HDNm2H9woJ1HIlUXbqMBq3oo8Bn+O0fEj1+qV3E7+RsTeTyVjY/TI1DP1A5niOvT0iLGWXd3F4sj1uqkBIuCLm75/EneXNwRidb8PZHCvlckLbAcN0sERupKFuk+BD3n2enVBPmPOL2O0LaKxMHTYwDbckp2VCKc4YjMKwahOkBZlFgERXgwFX+ubshlXv4TUDCtdOoP1pae6eOvFYFEbpwZWwG/PeYbqLCQ3wGRuekGBlyaWIlP9l93GhODQsuhItBba/8S3P+cDoaF1MMhoKnxOE1IWv8eKzlLHa0EUEEIlr4MIdNrqK0ZtAh8vuDSfOWL6XLFRnZvHftepoE0e5k7jUCfCPwlTCxM=
