dist: bionic

jobs:
  include:
  - name: Kong CE 2.0.x
    env: KONG_VERSION=2.0.x
  - name: Kong CE 2.1.x
    env: KONG_VERSION=2.1.x
  - name: Kong CE 2.2.x
    env: KONG_VERSION=2.2.x
  - name: Enterprise 2.1.4.x
    env: KONG_VERSION=2.1.4.x
  - name: Enterprise 2.2.0.x
    env: KONG_VERSION=2.2.0.x

env:
  global:
  # for Enterprise images
  - BINTRAY_USERNAME=kong-automation@kong
  - BINTRAY_REPO=kong
  - secure: oma6vvWWJ27k3XmianaLI3OC0pi1iIR32/3As7t0sdE+Z86s/qPDqjtrEAQV2e4mV+nSv90TIyIkM7+C9QkXD8lC8ekwhjepYupEjsqGtVZLqgxbwwXuFrqYd/ARtm6K6kGe9M93SAK3//CxtU7e902UcpDC6yVFN2ViuF1O7w8ObTTQ2z1ay+XONIwDPWlAenjlwp3gOCHCf2Gj/D4j7QjI1w56cCoB79gUbU9Ky90Nqrse2U6BClOjfutuFJ6cG7ztyvxoohh9Yji6uuzxbx5zn6v3Fex0YHNcjP72Bapchi2NOrB8ebfYDFwosAkHMgmCUa78Ws7n8k3X6KybfRW83fENcefnhcQnEJOzGIaJAHOoPlbkfu7b0V2C0KGMqSwpxEJZ+xsahj65yHLGaquDEYDZSID47Cy31QcS1jHPq3wjk/2NX5yEeFDK1gJVT4uqenInfCPUddSJ3D/9idiWszzMYm5kWmVKPNXXsTDb3NeadpX5WI5neV+eb67VPOc5EXpXA4BM/iNTbRU0A3dOJh47agyFZzPZepZyW9vEaVyoF7ycXNaf/jQX+NbYYe5GcmwYWCig2AQFlzHRiRRXp5XvxUd+h+ZixSKOOTl/NJ38gCaFOa+fEK9y3yHTwtelc+2iMBBjOQZV1SNSDWa0mdBOR8Y/GMmwb3Qzn10=
  # for Nightly Enterprise images
  - NIGHTLY_EE_USER=kong-automation@kong
  - secure: d8lQhUZik+Ng0+GueJzTn5+DXmWCW/Sx7eb+pbk8g5HJB4Myk3CGjdYb/wmn1oARpagQlMFCERdqYDY+NsVLL/m65aJkDsGiJYjxtE+EP7pai0gfpGD1tvBZ4te/YsbjdhNtj+nQ3nk0Ecc0S9+l99ztG7VjnBdfZbVOYLpJIzl/UNV5V/y00mdKkwTlGqppMe45XVqGdS/KkKMYm6w1OSs9YA4u9OpbzRmfvK5y1MRPNfRd1NY2+624bDEUZrPvicsofwDV7GhtPsr6hewGWmlA7/fINrE/rUaQKyFeeEkRQz7HCe9f7PlNHlPWD9nIGVbBNOaQqMmXlasdOqqMlJftukymiQdl1ALyZLa0y47MariOwzkU9aftcOQMsIwpuThWd1izzH+VVi9fWIFWvghD2MI5Ar+YxqRv2F1gLdhfte3Gaq+K8liKhiQG05GwxzWaJgAhoCY84KVh1zChjq4ZhN1zxWybEfaBboTYhKG82FKhRFppYfxLvNgUhRSBblWMsYpNsqapag4AL0GYiGnynTrlgRohHHCBSHt/6WZGOED8vCBKrd5e9iIWTK5WIipN6THQXdofA7xjbl6fEsdl5UiJc+vgRTuT96Te2LeLWswWdu0n1L+DEfLaPCPzxOXHElYe6NC/X1zsI4IEflUGHiNYS7oMkrHb4eEcz4g=

install:
- echo "$DOCKER_KEY" | docker login -u "$DOCKER_USER" --password-stdin
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: H7cwgmVIQGH4zIjwUdPEmEBCbnP0K696lEjx2g2L35uj4r9qt/3iwLzNLURTmz/R5Jlo6NZypCL8Zcv4ujSuh7UR1P/ob53Ca8az9y0vZsjz68HRrQ1UM9CljEN5Y/8F2J69wtfjx52LNC6BGVov0IyXTnUI/cLPylbgmyJoguUKnlsFo1WYn357R6dNwHS5n6jKAgGETvkhO1QCZuS15YX0BGIQw4Wt1OV1b/1T9Gm7JGLz51VrGig4G+V8mem040hju+wxJpKAcwxMqBhB/onu88CQjYjpVN2vHY5WTEdWCPjCU+BBAMGeiKt1nJVr5GQKFFdhvr8gmECSi7QKOi14kt40+1YUbq3ZwemZyTcIucFlMkvaGvOvDl8dRbPAe3Vy8Yh7hQAnFHdlVyYyfr0Tw5qnJrpDLVspmSbCy3J+vsafrEhXKQAsOhyU0ANmyEt0tJiXPA5DMQph/oACF24GIzlARDDfFvknGlXjA4D1VCtVUy90OWtQPBoNBinLAth60P5wIGF0k6/LX1I6iv+sJyCFlnCagVtzJI51frCU3rpg5K5CLUMvD11kTiZ8v61IVQrCahUkWfHYHl5dy7iDb9TdYoKSj1vPee/IYt4bOlPsECSMshIXAsz3cZfn2RLJhOBPEWzpdPiobpjST1+NACJUkD5qRZQBw6gknfg=
